apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-volume
    volumeAttributes:
      source: "//192.168.1.223/railtrack_sense_store"
    nodeStageSecretRef:
      name: smb-creds
      namespace: default
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=999
    - gid=999
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption